version: '3'

services:

  phpqa:
    image: jakzal/phpqa:latest
    volumes:
      - .:/project
    working_dir: /project

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'maJAhpnllJ41WELoT5pewLL9Bywf66b8mp+vq1ypobs='
      MERCURE_SUBSCRIBER_JWT_KEY: 'aJAhpnllJ41WELoT5pewLL9Bywf66b8mp+vq1ypobs='
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - "3000:80"
###< symfony/mercure-bundle ###

volumes:
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###

